# Generated by Django 3.0.6 on 2020-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metadata1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('pt', 'broblem type'), ('ft', 'finding type'), ('ps', 'problem status'), ('ss', 'solution status')], default='pt', max_length=2)),
            ],
        ),
    ]
